// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xvrxDBopVCbih82T6B34cmurCg3k8dw',
    appId: '1:356322095608:web:f8ab3d0b336048ea0fe60d',
    messagingSenderId: '356322095608',
    projectId: 'doit-a35c4',
    authDomain: 'doit-a35c4.firebaseapp.com',
    storageBucket: 'doit-a35c4.appspot.com',
    measurementId: 'G-F1HHPW7GZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbT-dns0cKKlYjCBFD6lT4zlJIPx8OvE0',
    appId: '1:356322095608:android:3de5fa6473c0c2550fe60d',
    messagingSenderId: '356322095608',
    projectId: 'doit-a35c4',
    storageBucket: 'doit-a35c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPvR4WfzvifWHebsrXT9_Gbk0BlaQKhDE',
    appId: '1:356322095608:ios:4302f841fc8b7d4d0fe60d',
    messagingSenderId: '356322095608',
    projectId: 'doit-a35c4',
    storageBucket: 'doit-a35c4.appspot.com',
    iosClientId:
        '356322095608-fs6phnniavj9ncirnfo3d5420jitatua.apps.googleusercontent.com',
    iosBundleId: 'com.example.doitApp',
  );
}
